/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '2/8/21 8:52 PM' with Gradle 3.0
 *
 * @author hp, @date 2/8/21 8:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
