/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '1/8/21 8:44 PM' with Gradle 3.0
 *
 * @author hp, @date 1/8/21 8:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
