/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '29/7/21 3:47 PM' with Gradle 3.0
 *
 * @author hp, @date 29/7/21 3:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
