/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '3/8/21 7:33 PM' with Gradle 3.0
 *
 * @author hp, @date 3/8/21 7:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
