/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '30/7/21 3:34 PM' with Gradle 3.0
 *
 * @author hp, @date 30/7/21 3:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
