/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '7/8/21 2:37 PM' with Gradle 3.0
 *
 * @author hp, @date 7/8/21 2:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
